apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-shipments
  labels:
    name: kafka-streams-shipments
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    name: kafka-streams-shipments
