---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: mirrormaker
  labels:
    strimzi.io/cluster: warehouse
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          name: mirrormaker-user
          key: password
    type: scram-sha-512
