---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: mm2
  labels:
    strimzi.io/cluster: warehouse
    app.kubernetes.io/instance: warehouse
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          name: mirrormaker-user
          key: password
    type: scram-sha-512
