apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sub.yaml
- kafka.yaml
- ./worldmap-front/is.yaml
- ./worldmap-front/deployment.yaml
- ./worldmap-front/service.yaml
- ./worldmap-front/route.yaml
# - warehouse-secret.yaml
# - warehouse-user.yaml 

