apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- sub.yaml
- ./kafka/kafka.yaml
- ./kafka/kafka-topics.yaml
- ./kafka/kafka-user.yaml
- ./kafka-streams-shipments/kafka-topics.yaml
- ./kafka-streams-shipments/kafka-user.yaml
- ./kafka-streams-shipments/service.yaml
- ./kafka-streams-shipments/statefulset.yaml
- ./worldmap-front/deployment.yaml
- ./worldmap-front/service.yaml
- ./worldmap-front/route.yaml
