apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patchesJson6902:
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-in"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "london-warehouse-in"
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-out"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "london-warehouse-out"
- target:
    kind: Integration
    group: camel.apache.org
    version: v1
    name: "kafkaintegration"
  patch: |-
     - op: replace
       path: "/spec/sources/0/content"
       value: |
          from("kamelet:mqtt-source?brokerUrl=tcp://mqtt-mqtt-0-svc:1883&topic=esp32&clientId=camel-k&username=admin&password=public")
          .convertBodyTo(String.class)
          .setBody({ e -> [ id: e.in.body, timestamp: new Date().getTime() ] })
          .marshal().json()
          //.to("log:info")
          .to("kamelet:kafka-sink-scram?bootstrapServers=warehouse-kafka-bootstrap:9092&user=camel&password=s3cr3t&topic=london-warehouse-in")