apiVersion: v1
kind: Secret
metadata:
  name: camel-config
type: Opaque
stringData:
  application.properties: |
    enricher.topic.athens.warehouse-in.direction=in
    enricher.topic.athens.warehouse-in.warehouse=ATH
    enricher.topic.athens.warehouse-out.direction=out
    enricher.topic.athens.warehouse-out.warehouse=ATH

    enricher.topic.brno.warehouse-in.direction=in
    enricher.topic.brno.warehouse-in.warehouse=BRN
    enricher.topic.brno.warehouse-out.direction=out
    enricher.topic.brno.warehouse-out.warehouse=BRN

    enricher.topic.brussels.warehouse-in.direction=in
    enricher.topic.brussels.warehouse-in.warehouse=BRU
    enricher.topic.brussels.warehouse-out.direction=out
    enricher.topic.brussels.warehouse-out.warehouse=BRU

    enricher.topic.bucharest.warehouse-in.direction=in
    enricher.topic.bucharest.warehouse-in.warehouse=BUC
    enricher.topic.bucharest.warehouse-out.direction=out
    enricher.topic.bucharest.warehouse-out.warehouse=BUC

    enricher.topic.dublin.warehouse-in.direction=in
    enricher.topic.dublin.warehouse-in.warehouse=DUB
    enricher.topic.dublin.warehouse-out.direction=out
    enricher.topic.dublin.warehouse-out.warehouse=DUB
 
    enricher.topic.lisboa-warehouse-in.direction=in
    enricher.topic.lisboa-warehouse-in.warehouse=LIS
    enricher.topic.lisboa-warehouse-out.direction=out
    enricher.topic.lisboa-warehouse-out.warehouse=LIS

    enricher.topic.london.warehouse-in.direction=in
    enricher.topic.london.warehouse-in.warehouse=LON
    enricher.topic.london.warehouse-out.direction=out
    enricher.topic.london.warehouse-out.warehouse=LON

    enricher.topic.paris.warehouse-in.direction=in
    enricher.topic.paris.warehouse-in.warehouse=PAR
    enricher.topic.paris.warehouse-out.direction=out
    enricher.topic.paris.warehouse-out.warehouse=PAR

    enricher.topic.stockholm.warehouse-in.direction=in
    enricher.topic.stockholm.warehouse-in.warehouse=STO
    enricher.topic.stockholm.warehouse-out.direction=out
    enricher.topic.stockholm.warehouse-out.warehouse=STO

    enricher.topic.varsovia.warehouse-in.direction=in
    enricher.topic.varsovia.warehouse-in.warehouse=VAR
    enricher.topic.varsovia.warehouse-out.direction=out
    enricher.topic.varsovia.warehouse-out.warehouse=VAR

    enricher.sink-topic=headquarter-location-records
    enricher.kafka-brokers=headquarter-kafka-bootstrap:9092
    enricher.kafka.security-protocol=SASL_PLAINTEXT
    enricher.kafka.sasl-mechanism=SCRAM-SHA-512
