apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: worldmap-front
    app.kubernetes.io/component: worldmap-front
    app.kubernetes.io/instance: worldmap-front
    app.kubernetes.io/name: worldmap-front
    app.kubernetes.io/part-of: worldmap-front
  name: worldmap-front
  namespace: headquarter
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/rhte2023edgelab/worldmap-front
    from:
      kind: DockerImage
      name: quay.io/rhte2023edgelab/worldmap-front
    name: latest
    referencePolicy:
      type: Local
