kind: Secret
apiVersion: v1
metadata:
  name: worldmap-front
stringData:
  password: s3cr3t
  sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='worldmap-front' password='s3cr3t';
type: Opaque