apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- name: NAMESPACE
  objref:
    kind: Kafka
    name: warehouse
    apiVersion: kafka.strimzi.io/v1beta2
  fieldref:
    fieldpath: metadata.name
- name: BROKER_NAME
  objref:
    name: mqtt
    kind: ActiveMQArtemis
    apiVersion: broker.amq.io/v1beta1

resources:
- AMQ/AMQaddress.yaml
- AMQ/broker.yaml
- AMQ/svc-mqtt-loadbalancer.yaml
- Camel/camel-secret.yaml
- Camel/camelUser.yaml
- Kafka/kafka.yaml
- Kafka/mirrormakeUser.yaml
- Kafka/mirrormaker-secret.yaml
- Kafka/topicKafka.yaml

# replacements:
# - source:
#     kind: KafkaTopic
#     name: warehouse-in
#     version: kafka.strimzi.io/v1beta2
#   targets:
#   - select: 
#       kind: KafkaTopic
#       name: warehouse-in
#     fieldPaths:
#     - metadata.[name=NAMESPACE]
