apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- broker.yaml
- AMQaddress.yaml
- svc-mqtt-loadbalancer.yaml
- mirrormaker-secret.yaml
- mirrormakeUser.yaml
- topicKafka.yaml
- camel-secret.yaml
- kafka.yaml

