kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: warehouse-in
  labels:
    strimzi.io/cluster: warehouse-paris
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: warehouse-out
  labels:
    strimzi.io/cluster: warehouse-paris
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
