apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: warehouse
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: warehouse-paris
      - namespace: warehouse-brussels
      - namespace: warehouse-london
      - namespace: warehouse-lisboa
      - namespace: warehouse-athens
      - namespace: warehouse-stockholm
      - namespace: warehouse-varsovia
      - namespace: warehouse-dublin
      - namespace: warehouse-bucharest
      - namespace: warehouse-brno
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: warehouse
      source:
        repoURL: https://github.com/RHTE-2023-Edge-Lab/rhte-gitops.git
        targetRevision: main
        path: warehouse/overlays/{{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=false
        automated:
          selfHeal: true
          prune: true
#        managedNamespaceMetadata:
#          labels:
#            argocd.argoproj.io/managed-by: openshift-gitops
