apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: warehouse
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: warehouse-01
      - namespace: warehouse-02
      - namespace: warehouse-03
      - namespace: warehouse-04
      - namespace: warehouse-05
      - namespace: warehouse-06
      - namespace: warehouse-07
      - namespace: warehouse-08
      - namespace: warehouse-09
      - namespace: warehouse-10
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: warehouse
      source:
        repoURL: https://github.com/RHTE-2023-Edge-Lab/rhte-gitops.git
        targetRevision: main
        path: warehouse/base
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
