apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: warehouse
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/RHTE-2023-Edge-Lab/rhte-gitops.git
status: {}
