apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patchesJson6902:
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-in"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "athens-warehouse-in"
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-out"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "athens-warehouse-out"
- target:
    kind: Integration
    group: camel.apache.org
    version: v1
    name: "kafkaintegration"
  patch: |-
     - op: replace
       path: "/spec/sources/0/content"
       value: |
          from("paho:esp8266-out?brokerUrl=tcp://mqtt-mqtt-0-svc:1883&userName=admin&password=public")
          .convertBodyTo(String.class)
          .setBody({ e -> [ parcelNumber: e.in.body, timestamp: new Date().getTime() ] })
          .marshal().json()
          //.to("log:info")
          .to("kamelet:kafka-sink-scram?bootstrapServers=warehouse-kafka-bootstrap:9092&user=camel&password=s3cr3t&topic=athens-warehouse-in")
- target:
    kind: Secret
    version: v1
    name: "warehouse-user"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-athens-user"
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-athens"
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-athens
         strimzi.io/cluster: warehouse-athens
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "camel"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-athens
         strimzi.io/cluster: warehouse-athens
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "mirrormaker"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-athens
         strimzi.io/cluster: warehouse-athens
- target:
    kind: Kafka
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-athens"
