apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-headquarter
  labels:
    strimzi.io/cluster: headquarter
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-headquarter
          key: password
    type: scram-sha-512
