apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headquarter
  namespace: argocd
spec:
  project: headquarter
  source:
    repoURL: https://github.com/RHTE-2023-Edge-Lab/rhte-gitops.git
    targetRevision: main
    path: headquarter/
  destination:
    server: https://api.cluster-dw5m6.dw5m6.sandbox1231.opentlc.com:6443
    namespace: headquarter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
