apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patchesJson6902:
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-in"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "stockholm-warehouse-in"
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-out"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "stockholm-warehouse-out"
- target:
    kind: Integration
    group: camel.apache.org
    version: v1
    name: "kafkaintegration"
  patch: |-
     - op: replace
       path: "/spec/sources/0/content"
       value: |
          from("kamelet:mqtt-source?brokerUrl=tcp://mqtt-mqtt-0-svc:1883&topic=esp32&clientId=camel-k&username=admin&password=public")
          .convertBodyTo(String.class)
          .setBody({ e -> [ id: e.in.body, timestamp: new Date().getTime() ] })
          .marshal().json()
          //.to("log:info")
          .to("kamelet:kafka-sink-scram?bootstrapServers=warehouse-kafka-bootstrap:9092&user=camel&password=s3cr3t&topic=stockholm-warehouse-in")- target:
    kind: Secret
    version: v1
    name: "warehouse-user"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-stockholm-user"
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-stockholm"
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-stockholm
         strimzi.io/cluster: warehouse-stockholm
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "camel"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-stockholm
         strimzi.io/cluster: warehouse-stockholm
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "mirrormaker"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-stockholm
         strimzi.io/cluster: warehouse-stockholm
- target:
    kind: Kafka
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-stockholm"
