kind: ActiveMQArtemisAddress
apiVersion: broker.amq.io/v1beta1
metadata:
  name: esp8266-in
spec:
  addressName: esp8266-in
  queueName: myQueue0
  routingType: anycast
---
kind: ActiveMQArtemisAddress
apiVersion: broker.amq.io/v1beta1
metadata:
  name: esp8266-out
spec:
  addressName: esp8266-out
  queueName: myQueue0
  routingType: anycast

