apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patchesJson6902:
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-in"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "brno-warehouse-in"
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-out"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "brno-warehouse-out"
- target:
    kind: Integration
    group: camel.apache.org
    version: v1
    name: "kafkaintegration"
  patch: |-
     - op: replace
       path: "/spec/sources/0/content"
       value: |
          from("paho:esp8266-out?brokerUrl=tcp://mqtt-mqtt-0-svc:1883&userName=admin&password=public")
          .convertBodyTo(String.class)
          .setBody({ e -> [ parcelNumber: e.in.body, timestamp: new Date().getTime() ] })
          .marshal().json()
          //.to("log:info")
          .to("kamelet:kafka-sink-scram?bootstrapServers=warehouse-kafka-bootstrap:9092&user=camel&password=s3cr3t&topic=brno-warehouse-in")
- target:
    kind: Secret
    version: v1
    name: "warehouse-user"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-brno"
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "warehouse-brno"
     - op: replace
       path: "/spec/authentication/password/valueFrom/secretKeyRef/name"
       value: "warehouse-brno"
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-brno
         strimzi.io/cluster: warehouse-brno
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "camel"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-brno
         strimzi.io/cluster: warehouse-brno
- target:
    kind: KafkaUser
    group: kafka.strimzi.io
    version: v1beta2
    name: "mirrormaker"
  patch: |-
     - op: add
       path: "/metadata/labels"
       value: 
         app.kubernetes.io/instance: warehouse-brno
         strimzi.io/cluster: warehouse-brno
- target:
    kind: KafkaMirrorMaker
    group: kafka.strimzi.io
    version: v1beta2
    name: mirrormaker
  patch: |-
    - op: replace
      path: "/spec/consumer/groupId"
      value: "gid-brno"
    - op: replace
      path: "/spec/consumer/authentication/passwordSecret/secretName"
      value: "warehouse-brno"
    - op: replace
      path: "/spec/consumer/authentication/username"
      value: "warehouse-brno"
    - op: replace
      path: "/spec/producer/bootstrapServers"
      value: "headquarter-kafka-tls-bootstrap-headquarter.apps.cluster-cgc8r.cgc8r.sandbox587.opentlc.com"
    - op: replace
      path: "/spec/producer/authentication/passwordSecret/secretName"
      value: "headquarter-brno"
    - op: replace
      path: "/spec/producer/authentication/username"
      value: "warehouse-brno"
- target:
    kind: Secret
    version: v1
    name: headquarter-<CITY>
  patch: |-
    - op: replace
      path: "/metadata/name"
      value: "headquarter-brno"