---
kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-rhte
  namespace: openshift-config
data:
  htpasswd: >-
    YXRoZW5zLXRlYW06JDJ5JDA1JEZjdThYQWNqaU5lSnV1R2VJdmxSS3V2dFVQWWhCb052c3hMdG1sTE1hNmVlUjU0OUtvTWhXCmJybm8tdGVhbTokMnkkMDUkckkuWUs2ZjloWS5DYUhvMEZldGNOZS93S3guZjQ1aU9GMjZzS2J2eml5Wm43SHgwRTY1WUMKYnJ1c3NlbHMtdGVhbTokMnkkMDUkSWljY2F2alM2Ry5lbjFlOHpSdS8vZWsyLkdJcVA1TWd4bUt6aC5RekFiNEh5cXR2S2wwbTYKYnVjaGFyZXN0LXRlYW06JDJ5JDA1JGQuQnZGcjYwUUFUcFJYOE1wWC5UTi51ZTR5a2RvWmNkZy5FL3BNcjkwUEM3LzQxaC5LeTcuCmR1Ymxpbi10ZWFtOiQyeSQwNSRlbmpSajFSYkRIaHQ3S002RkdPRjl1RXVMTjFOSFdzLzNncU5ramJBTlVvT2xNdWticFM0cQpsaXNib2EtdGVhbTokMnkkMDUkc3U2LlgxNGE3S292REp3SFdkUVBFZW1uem9BVmN3aTdwUGE2YjducFZFVnZGaFBnUXdudy4KbG9uZG9uLXRlYW06JDJ5JDA1JFNvVkhET1ZoU3ZiVFRFV2l1d3RoVHVMQjhsWVNkNktQZzJqZFF1M1dZcEV4QWg1Mkx4YlZhCnBhcmlzLXRlYW06JDJ5JDA1JFlGUEpZckNrNUFUVGlTY1pxeDByMXV6d0FrbVNqazNubG85cUREaVdkamtLeFJrMmxTOUtDCnN0b2Nrb2xtLXRlYW06JDJ5JDA1JE5mTXV1LmdxbmlwMjc3NjFYMDR3NXUyZ2JONlB1RzZZRHE2Sm9yd29vLkxOVEIxdjVoY3NTCnZhcnNvdmlhLXRlYW06JDJ5JDA1JEVLTVptTzhRbTdsNjN2cEx2OVNCby45bUJNRDVzWnE0ZVkxUFB2NUhHYWIzQkdYTDYub3VT
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: claim
      name: htpasswd_provider
      type: HTPasswd
    - htpasswd:
        fileData:
          name: htpasswd-rhte
      mappingMethod: claim
      name: htpasswd_rhte
      type: HTPasswd
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: athens-team
  namespace: warehouse-athens
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: athens-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brno-team
  namespace: warehouse-brno
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: brno-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: brussels-team
  namespace: warehouse-brussels
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: brussels-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bucharest-team
  namespace: warehouse-bucharest
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bucharest-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dublin-team
  namespace: warehouse-dublin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: dublin-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lisboa-team
  namespace: warehouse-lisboa
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: lisboa-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lisboa-team
  namespace: warehouse-lisboa
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: lisboa-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: paris-team
  namespace: warehouse-paris
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: paris-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stockolm-team
  namespace: warehouse-stockolm
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: stockolm-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: varsovia-team
  namespace: warehouse-varsovia
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: varsovia-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
