apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patchesJson6902:
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-in"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "dublin-warehouse-in"
- target:
    kind: KafkaTopic
    group: kafka.strimzi.io
    version: v1beta2
    name: "warehouse-out"
  patch: |-
     - op: replace
       path: "/metadata/name"
       value: "dublin-warehouse-out"
